const RESERVED_CREDENTIAL_ENV_NAMES = new Set([
  "_",
  "ALL_PROXY",
  "BASH_ENV",
  "BASHOPTS",
  "BUNDLE_GEMFILE",
  "CDPATH",
  "CI",
  "COMSPEC",
  "CURL_CA_BUNDLE",
  "ELECTRON_RUN_AS_NODE",
  "ENV",
  "GH_TOKEN",
  "GLIBC_TUNABLES",
  "GOPATH",
  "GOROOT",
  "HOME",
  "HOSTNAME",
  "HTTPS_PROXY",
  "HTTP_PROXY",
  "IFS",
  "JAVA_TOOL_OPTIONS",
  "LANG",
  "LOGNAME",
  "NO_COLOR",
  "NO_PROXY",
  "NODE_OPTIONS",
  "NODE_PATH",
  "OLDPWD",
  "OPENSSL_CONF",
  "PATH",
  "PATHEXT",
  "PERL5LIB",
  "PERL5OPT",
  "POSIXLY_CORRECT",
  "PROGRAMDATA",
  "PROGRAMFILES",
  "PS4",
  "PWD",
  "REQUESTS_CA_BUNDLE",
  "RUBYLIB",
  "RUBYOPT",
  "SHELL",
  "SHELLOPTS",
  "SHLVL",
  "SSH_AGENT_PID",
  "SSH_AUTH_SOCK",
  "SSL_CERT_DIR",
  "SSL_CERT_FILE",
  "SSLKEYLOGFILE",
  "SYSTEMROOT",
  "TEMP",
  "TERM",
  "TMP",
  "TMPDIR",
  "TZ",
  "USER",
  "USERPROFILE",
  "UV_THREADPOOL_SIZE",
  "WINDIR",
]);

const RESERVED_CREDENTIAL_ENV_PREFIXES = [
  "AGENTCI_",
  "ACTIONS_",
  "BASH_FUNC_",
  "CARGO_",
  "DYLD_",
  "GIT_",
  "GITHUB_",
  "JAVA_",
  "JDK_",
  "LC_",
  "LD_",
  "MALLOC_",
  "NODE_",
  "NPM_",
  "PNPM_",
  "PYTHON",
  "RUNNER_",
  "RUST_",
  "XDG_",
] as const;

/** Names that can alter process/runtime startup are never credential channels. */
export function isReservedCredentialEnvironmentName(name: string): boolean {
  return (
    RESERVED_CREDENTIAL_ENV_NAMES.has(name) ||
    RESERVED_CREDENTIAL_ENV_PREFIXES.some((prefix) => name.startsWith(prefix))
  );
}
